[package]
name = "uu_rm"
description = "rm ~ (uutils) remove PATHNAME"
repository = "https://github.com/uutils/coreutils/tree/main/src/uu/rm"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
edition.workspace = true
readme.workspace = true

[lints]
workspace = true

[lib]
path = "src/rm.rs"

[dependencies]
thiserror = { workspace = true }
clap = { workspace = true }
fluent = { workspace = true }
indicatif = { workspace = true }

# safe-traversal is only available on Linux
[target.'cfg(target_os = "linux")'.dependencies]
uucore = { workspace = true, features = ["fs", "parser", "safe-traversal"] }
libc = { workspace = true }

# Non-Linux Unix platforms
[target.'cfg(all(unix, not(target_os = "linux")))'.dependencies]
uucore = { workspace = true, features = ["fs", "parser"] }
libc = { workspace = true }

# Windows
[target.'cfg(windows)'.dependencies]
uucore = { workspace = true, features = ["fs", "parser"] }
windows-sys = { workspace = true, features = ["Win32_Storage_FileSystem"] }

# WASI
[target.'cfg(target_os = "wasi")'.dependencies]
uucore = { workspace = true, features = ["fs", "parser"] }

[[bin]]
name = "rm"
path = "src/main.rs"

[dev-dependencies]
divan = { workspace = true }
tempfile = { workspace = true }
uucore = { workspace = true, features = ["benchmark"] }

[[bench]]
name = "rm_bench"
harness = false
